### ISSUE TITLE
Crash after Computer Sleeps

### ISSUE THREAD

**Issue by nfehrenbach** [OneSunSolar/IVScan#22] opened 2017-07-06 23:11 UTC
Program was working with long (minutes - hours) delay between scans. Returned after longer period and the computer was asleep. Keithley responded, but error stating device couldn't connect arose. A subsequent attempt blanked the 4-point resistance tab and made the program unresponsive. Keithley again responded, but no data displayed. I suspect the graph drawing application, however the terminals were correct as no change in input had occurred between last successful usage.
[ivscan-2017-07-06.txt](https://github.com/OneSunSolar/IVScan/files/1129506/ivscan-2017-07-06.txt)

**Comment by markbreynolds** [comment] 2017-07-06 23:52
I disabled USB power saving on that computer again so let me know if it happens again. Regardless, I will make graphing more robust.

**Comment by markbreynolds** [comment] 2017-07-13 21:19
If this issue does not come up again in 7 days, we will close this issue.

**Comment by markbreynolds** [comment] 2017-07-20 16:49
Unable to reproduce.

**Closed by markbreynolds** 2017-07-20 16:49 UTC
